version: 2.1
executors:
  base:
    machine:
      docker_layer_caching: true
jobs:
  build:
    executor: base
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:55:81:26:1a:74:cd:f9:ba:e3:55:1d:67:3e:77:2f"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - packages/**/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
            - packages/**/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  build:
    jobs:
      - build